---
title: "quick recipes!!"
description: |
  A new article created using the Distill format.
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

our first DELICOUS recipe is for hasty people with big appetites! 


Ingredients

½ red onion, thinly sliced
1 tbsp olive oil
½ tbsp cider vinegar
2 tbsp natural yogurt
1 tbsp tahini
1 small garlic clove, crushed
1½ tsp cumin powder
½ tsp ground coriander
1 tsp paprika
2 chicken breasts
1 tbsp vegetable oil
4 flour tortilla wraps
4 tomatoes, thinly sliced
1 avocado, stoned, peeled and sliced











Method
STEP 1
Heat a dry griddle pan over a medium-high heat, and fry the aubergine rounds for 2 mins on each side until lightly coloured and char lines appear (you may need to do this in batches). Transfer to a bowl with the onions, then toss with the olive oil and vinegar.

STEP 2
Combine the yogurt, tahini and garlic in a bowl with 1 tbsp water to loosen. Mix the cumin, coriander, paprika and some salt and pepper in a small bowl. Put the chicken on a board, cover with baking parchment and bash with a rolling pin to an even 1½cm thickness. Rub all over with the spice mix, leave for 10 mins, then fry in the oil for 12 mins, flipping after 8 mins. Transfer to a board, rest briefly, then slice.

STEP 3
Warm the wraps in a dry frying pan, then fill with the tomatoes, aubergine and onion mix, avocado, chicken and tahini dressing.






